### PR TITLE
Derive Debug, Clone and PartialEq for AST-types

### PR DESCRIPTION
**Pull request by Luro02**

### CODE REVIEW

**Comment by rhysd** [comment]
I intentionally did not derive them. Deriving unnecessary traits unnecessarily makes binary bigger.

**Comment by Luro02** [comment]
Compiling `wain` with my branch:
```
lucas@luna:/media/hdd/home/projects/wain$ ls -l --size bytes target/release/wain
.rwxr-xr-x lucas users 3888384  Fri Jul 31 21:07:48 2020  wain
```

Compiling `wain` with master of my fork:
```
lucas@luna:/media/hdd/home/projects/wain$ ls -l --size bytes target/release/wain
.rwxr-xr-x lucas users 3888384  Fri Jul 31 21:05:21 2020  wain
```

As you can see the file size is identical, because the compiler is smart enough to remove redundant code. As long as you do not use the debug implementations the binary size won't increase.

---

I made this PR, because I want to use your crate in my own project. While developing I would sometimes like to know how the data is parsed into the structs and what each struct contains, but without the Debug trait it is very difficult to print out the data.

**Comment by rhysd** [comment]
I'm sorry that not making binary bigger but compiling more slowly.

Actually I tried it as follows:

- master

```
> cargo clean
~/Develop/github.com/rhysd/wain
> time cargo build 2>/dev/null
cargo build 2> /dev/null  12.28s user 1.10s system 314% cpu 4.250 total
```

- your branch

```
> cargo clean
~/Develop/github.com/rhysd/wain
> time cargo build 2>/dev/null
cargo build 2> /dev/null  12.71s user 1.13s system 311% cpu 4.440 total
```

---

> I made this PR, because I want to use your crate in my own project.

OK, actually I'm not opposing this PR. I just wanted to know the reason.

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
I published wain-ast v0.2.1. It should be available via `cargo`.

**Comment by Luro02** [comment]
Thank you very much :)

**Pull request merged**
